name: realynx_app_container

services: 

  realynx_django_app:
    build: .
    volumes:
      - .:/realynx_container_root
    ports:
      - 8000:8000
    image: realynx_django
    container_name: realynx_django_app
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: realynx_postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
